<a href="https://colab.research.google.com/github/anishkr-sahu/Genai/blob/main/Genai_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/IMDB Dataset.csv")

In [ ]:
df

,ever,the story is so thin that you can watch television through it,and the whole film has so many holes you could drive an oil tanker through it.<br /><br />Sure,I appreciate a good B-movie as much as most male white homo sapiens do. But this has got to be the worst I've seen. In fact it's so B that it lacks everything that makes a B-movie interesting.<br /><br />The whole movie is based around such charming artefacts as the characters beating the crap out of each other,various bodily functions and the complete lack of sanity of anything on-screen.<br /><br />It's not even funny. In fact it's quite the opposite. I found it even boring at times due to it's extreme predictability.<br /><br />I find nothing good to say about this movie. It was a waste of time watching it,"and I hope others don't do the same mistake. If you also pay for it you should get a serious brainscan done.""",negative
0,"Loosely based on novels by Earl Derr Biggers, ...",negative,NaN,NaN,NaN,NaN,NaN
1,This is one awful movie!! Some people told me ...,negative,NaN,NaN,NaN,NaN,NaN
2,That's My Bush is a live action project made b...,positive,NaN,NaN,NaN,NaN,NaN
3,Full disclosure: I'm a cynic. I like my ending...,positive,NaN,NaN,NaN,NaN,NaN
4,I didn't catch Gilmore Girls when it first cam...,positive,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
13561,I thought this movie did a down right good job...,positive,NaN,NaN,NaN,NaN,NaN
13562,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,NaN,NaN,NaN,NaN,NaN
13563,I am a Catholic taught in parochial elementary...,negative,NaN,NaN,NaN,NaN,NaN
13564,I'm going to have to disagree with the previou...,negative,NaN,NaN,NaN,NaN,NaN
13565,No one expects the Star Trek movies to be high...,negative,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(13566, 7)

In [ ]:
df.head()

,ever,the story is so thin that you can watch television through it,and the whole film has so many holes you could drive an oil tanker through it.<br /><br />Sure,I appreciate a good B-movie as much as most male white homo sapiens do. But this has got to be the worst I've seen. In fact it's so B that it lacks everything that makes a B-movie interesting.<br /><br />The whole movie is based around such charming artefacts as the characters beating the crap out of each other,various bodily functions and the complete lack of sanity of anything on-screen.<br /><br />It's not even funny. In fact it's quite the opposite. I found it even boring at times due to it's extreme predictability.<br /><br />I find nothing good to say about this movie. It was a waste of time watching it,"and I hope others don't do the same mistake. If you also pay for it you should get a serious brainscan done.""",negative
0,"Loosely based on novels by Earl Derr Biggers, ...",negative,NaN,NaN,NaN,NaN,NaN
1,This is one awful movie!! Some people told me ...,negative,NaN,NaN,NaN,NaN,NaN
2,That's My Bush is a live action project made b...,positive,NaN,NaN,NaN,NaN,NaN
3,Full disclosure: I'm a cynic. I like my ending...,positive,NaN,NaN,NaN,NaN,NaN
4,I didn't catch Gilmore Girls when it first cam...,positive,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.head(10)

,ever,the story is so thin that you can watch television through it,and the whole film has so many holes you could drive an oil tanker through it.<br /><br />Sure,I appreciate a good B-movie as much as most male white homo sapiens do. But this has got to be the worst I've seen. In fact it's so B that it lacks everything that makes a B-movie interesting.<br /><br />The whole movie is based around such charming artefacts as the characters beating the crap out of each other,various bodily functions and the complete lack of sanity of anything on-screen.<br /><br />It's not even funny. In fact it's quite the opposite. I found it even boring at times due to it's extreme predictability.<br /><br />I find nothing good to say about this movie. It was a waste of time watching it,"and I hope others don't do the same mistake. If you also pay for it you should get a serious brainscan done.""",negative
0,"Loosely based on novels by Earl Derr Biggers, ...",negative,NaN,NaN,NaN,NaN,NaN
1,This is one awful movie!! Some people told me ...,negative,NaN,NaN,NaN,NaN,NaN
2,That's My Bush is a live action project made b...,positive,NaN,NaN,NaN,NaN,NaN
3,Full disclosure: I'm a cynic. I like my ending...,positive,NaN,NaN,NaN,NaN,NaN
4,I didn't catch Gilmore Girls when it first cam...,positive,NaN,NaN,NaN,NaN,NaN
5,"I had high hopes going to see this, as I alway...",negative,NaN,NaN,NaN,NaN,NaN
6,A pleasant surprise! I expected a further down...,positive,NaN,NaN,NaN,NaN,NaN
7,"To quote Flik, that was my reaction exactly: W...",positive,NaN,NaN,NaN,NaN,NaN
8,"Daniel Day-Lewis is Christy Brown, a victim of...",positive,NaN,NaN,NaN,NaN,NaN
9,I think this movie is a very funny film and on...,positive,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.drop(columns=["and the whole film has so many holes you could drive an oil tanker through it.<br /><br />Sure",'I appreciate a good B-movie as much as most male white homo sapiens do. But this has got to be the worst I\'ve seen. In fact it\'s so B that it lacks everything that makes a B-movie interesting.<br /><br />The whole movie is based around such charming artefacts as the characters beating the crap out of each other'], errors='ignore')

,ever,the story is so thin that you can watch television through it,and the whole film has so many holes you could drive an oil tanker through it.<br /><br />Sure,I appreciate a good B-movie as much as most male white homo sapiens do. But this has got to be the worst I've seen. In fact it's so B that it lacks everything that makes a B-movie interesting.<br /><br />The whole movie is based around such charming artefacts as the characters beating the crap out of each other,various bodily functions and the complete lack of sanity of anything on-screen.<br /><br />It's not even funny. In fact it's quite the opposite. I found it even boring at times due to it's extreme predictability.<br /><br />I find nothing good to say about this movie. It was a waste of time watching it,"and I hope others don't do the same mistake. If you also pay for it you should get a serious brainscan done.""",negative
0,"Loosely based on novels by Earl Derr Biggers, ...",negative,NaN,NaN,NaN,NaN,NaN
1,This is one awful movie!! Some people told me ...,negative,NaN,NaN,NaN,NaN,NaN
2,That's My Bush is a live action project made b...,positive,NaN,NaN,NaN,NaN,NaN
3,Full disclosure: I'm a cynic. I like my ending...,positive,NaN,NaN,NaN,NaN,NaN
4,I didn't catch Gilmore Girls when it first cam...,positive,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
13561,I thought this movie did a down right good job...,positive,NaN,NaN,NaN,NaN,NaN
13562,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,NaN,NaN,NaN,NaN,NaN
13563,I am a Catholic taught in parochial elementary...,negative,NaN,NaN,NaN,NaN,NaN
13564,I'm going to have to disagree with the previou...,negative,NaN,NaN,NaN,NaN,NaN
13565,No one expects the Star Trek movies to be high...,negative,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.drop(columns=[
    ' and the whole film has so many holes you could drive an oil tanker through it.<br /><br />Sure',
    " I appreciate a good B-movie as much as most male white homo sapiens do. But this has got to be the worst I've seen. In fact it's so B that it lacks everything that makes a B-movie interesting.<br /><br />The whole movie is based around such charming artefacts as the characters beating the crap out of each other",
    " various bodily functions and the complete lack of sanity of anything on-screen.<br /><br />It's not even funny. In fact it's quite the opposite. I found it even boring at times due to it's extreme predictability.<br /><br />I find nothing good to say about this movie. It was a waste of time watching it",
    ' and I hope others don\'t do the same mistake. If you also pay for it you should get a serious brainscan done."',
    'negative'
], errors='ignore')

In [ ]:
df

,ever,the story is so thin that you can watch television through it,and the whole film has so many holes you could drive an oil tanker through it.<br /><br />Sure,I appreciate a good B-movie as much as most male white homo sapiens do. But this has got to be the worst I've seen. In fact it's so B that it lacks everything that makes a B-movie interesting.<br /><br />The whole movie is based around such charming artefacts as the characters beating the crap out of each other,various bodily functions and the complete lack of sanity of anything on-screen.<br /><br />It's not even funny. In fact it's quite the opposite. I found it even boring at times due to it's extreme predictability.<br /><br />I find nothing good to say about this movie. It was a waste of time watching it,"and I hope others don't do the same mistake. If you also pay for it you should get a serious brainscan done.""",negative
0,"Loosely based on novels by Earl Derr Biggers, ...",negative,NaN,NaN,NaN,NaN,NaN
1,This is one awful movie!! Some people told me ...,negative,NaN,NaN,NaN,NaN,NaN
2,That's My Bush is a live action project made b...,positive,NaN,NaN,NaN,NaN,NaN
3,Full disclosure: I'm a cynic. I like my ending...,positive,NaN,NaN,NaN,NaN,NaN
4,I didn't catch Gilmore Girls when it first cam...,positive,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
13561,I thought this movie did a down right good job...,positive,NaN,NaN,NaN,NaN,NaN
13562,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,NaN,NaN,NaN,NaN,NaN
13563,I am a Catholic taught in parochial elementary...,negative,NaN,NaN,NaN,NaN,NaN
13564,I'm going to have to disagree with the previou...,negative,NaN,NaN,NaN,NaN,NaN
13565,No one expects the Star Trek movies to be high...,negative,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.rename(columns={'ever': 'review', ' the story is so thin that you can watch television through it': 'sentiment'})
display(df.head())

,review,sentiment,and the whole film has so many holes you could drive an oil tanker through it.<br /><br />Sure,I appreciate a good B-movie as much as most male white homo sapiens do. But this has got to be the worst I've seen. In fact it's so B that it lacks everything that makes a B-movie interesting.<br /><br />The whole movie is based around such charming artefacts as the characters beating the crap out of each other,various bodily functions and the complete lack of sanity of anything on-screen.<br /><br />It's not even funny. In fact it's quite the opposite. I found it even boring at times due to it's extreme predictability.<br /><br />I find nothing good to say about this movie. It was a waste of time watching it,"and I hope others don't do the same mistake. If you also pay for it you should get a serious brainscan done.""",negative
0,"Loosely based on novels by Earl Derr Biggers, ...",negative,NaN,NaN,NaN,NaN,NaN
1,This is one awful movie!! Some people told me ...,negative,NaN,NaN,NaN,NaN,NaN
2,That's My Bush is a live action project made b...,positive,NaN,NaN,NaN,NaN,NaN
3,Full disclosure: I'm a cynic. I like my ending...,positive,NaN,NaN,NaN,NaN,NaN
4,I didn't catch Gilmore Girls when it first cam...,positive,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['review'][0]

'Loosely based on novels by Earl Derr Biggers, 20th Century Fox\'s Charlie Chan series proved an audience favorite--but when Japan attacked Pearl Harbor the studio feared audiences would turn against its Asian hero. This was a miscalculation: actor Sidney Toler took the role to "poverty row" Monogram Studios, where he continued to portray the character in eleven more films made between 1944 and his death in 1947.<br /><br />20th Century Fox had regarded the Chan films as inexpensive "B" movies, but even so the studio took considerable care with them: the plots were often silly, but the pace was sharp, the dialogue witty, and the casts (which featured the likes of Bela Lugosi and Ray Milland) always expert. The result was a kindly charm which has stood the test of time. Monogram was a different matter: Chan films were "B" movies plain and simple. Little care was taken with scripts or cast and resulting films were flat, mediocre at best, virtually unwatchable at worst.<br /><br />Thanks to an adequate cast and a few interesting plot devices, THE SHANGHAI COBRA is among the best of the Monogram-made Chan films--but even so it barely manages to achieve a consistent mediocrity. In this particularly entry, Chan (Sidney Toler) is called upon to investigate a murderer who kills with what appears to be a cobra-like bite; at the same time, he decides to make certain that a government supply of radium tucked away in a bank vault, of all places, remains secure. Do these two seemingly unrelated plot lines come together? Well... could be! Sidney Toler is always enjoyable as Chan, but most of his Monogram performances seemed "phoned in"--and that is as true of COBRA as it is of any Monogram Chan film. As usual, the really enjoyable performer is Mantan Mooreland. Changing times have led us to look upon Moreland\'s brand of comedy as demeaning to African-Americans, but he was an expert actor and comic, and taken within the context of what was possible for a black actor in the 1940s his work has tremendous charm and innocence.<br /><br />Fans of the 20th Century Fox series are likely to find Monogram\'s Chan a significant disappointment and newcomers who like the Monogram films will probably consider them third-rate after encountering the Fox films. Like other Monogram Chan films, THE SHANGHAI COBRA is best left to determined collectors. Four stars, and that\'s being generous.<br /><br />GFT, Amazon Reviewer'

Remove html tags

In [ ]:
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'',text)

In [ ]:
df['review'] = df['review'].apply(remove_html_tags)

In [ ]:
df['review'][0]

'Loosely based on novels by Earl Derr Biggers, 20th Century Fox\'s Charlie Chan series proved an audience favorite--but when Japan attacked Pearl Harbor the studio feared audiences would turn against its Asian hero. This was a miscalculation: actor Sidney Toler took the role to "poverty row" Monogram Studios, where he continued to portray the character in eleven more films made between 1944 and his death in 1947.20th Century Fox had regarded the Chan films as inexpensive "B" movies, but even so the studio took considerable care with them: the plots were often silly, but the pace was sharp, the dialogue witty, and the casts (which featured the likes of Bela Lugosi and Ray Milland) always expert. The result was a kindly charm which has stood the test of time. Monogram was a different matter: Chan films were "B" movies plain and simple. Little care was taken with scripts or cast and resulting films were flat, mediocre at best, virtually unwatchable at worst.Thanks to an adequate cast and a few interesting plot devices, THE SHANGHAI COBRA is among the best of the Monogram-made Chan films--but even so it barely manages to achieve a consistent mediocrity. In this particularly entry, Chan (Sidney Toler) is called upon to investigate a murderer who kills with what appears to be a cobra-like bite; at the same time, he decides to make certain that a government supply of radium tucked away in a bank vault, of all places, remains secure. Do these two seemingly unrelated plot lines come together? Well... could be! Sidney Toler is always enjoyable as Chan, but most of his Monogram performances seemed "phoned in"--and that is as true of COBRA as it is of any Monogram Chan film. As usual, the really enjoyable performer is Mantan Mooreland. Changing times have led us to look upon Moreland\'s brand of comedy as demeaning to African-Americans, but he was an expert actor and comic, and taken within the context of what was possible for a black actor in the 1940s his work has tremendous charm and innocence.Fans of the 20th Century Fox series are likely to find Monogram\'s Chan a significant disappointment and newcomers who like the Monogram films will probably consider them third-rate after encountering the Fox films. Like other Monogram Chan films, THE SHANGHAI COBRA is best left to determined collectors. Four stars, and that\'s being generous.GFT, Amazon Reviewer'

Remove url

In [ ]:

def remove_url(text):
  pattern = re.compile(r'https?://\S+/www\.\S+')
  return pattern.sub(r'',text)

In [ ]:
df['review'] = df['review'].apply(remove_url)

Punctuation handling

In [ ]:

import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude = string.punctuation
def remove_punc(text):
  for char in exclude:
    text = text.replace(char,'')
  return text

In [ ]:
df['review'] = df['review'].apply(remove_punc)

In [ ]:
df['review'][0]

'Loosely based on novels by Earl Derr Biggers 20th Century Foxs Charlie Chan series proved an audience favoritebut when Japan attacked Pearl Harbor the studio feared audiences would turn against its Asian hero This was a miscalculation actor Sidney Toler took the role to poverty row Monogram Studios where he continued to portray the character in eleven more films made between 1944 and his death in 194720th Century Fox had regarded the Chan films as inexpensive B movies but even so the studio took considerable care with them the plots were often silly but the pace was sharp the dialogue witty and the casts which featured the likes of Bela Lugosi and Ray Milland always expert The result was a kindly charm which has stood the test of time Monogram was a different matter Chan films were B movies plain and simple Little care was taken with scripts or cast and resulting films were flat mediocre at best virtually unwatchable at worstThanks to an adequate cast and a few interesting plot devices THE SHANGHAI COBRA is among the best of the Monogrammade Chan filmsbut even so it barely manages to achieve a consistent mediocrity In this particularly entry Chan Sidney Toler is called upon to investigate a murderer who kills with what appears to be a cobralike bite at the same time he decides to make certain that a government supply of radium tucked away in a bank vault of all places remains secure Do these two seemingly unrelated plot lines come together Well could be Sidney Toler is always enjoyable as Chan but most of his Monogram performances seemed phoned inand that is as true of COBRA as it is of any Monogram Chan film As usual the really enjoyable performer is Mantan Mooreland Changing times have led us to look upon Morelands brand of comedy as demeaning to AfricanAmericans but he was an expert actor and comic and taken within the context of what was possible for a black actor in the 1940s his work has tremendous charm and innocenceFans of the 20th Century Fox series are likely to find Monograms Chan a significant disappointment and newcomers who like the Monogram films will probably consider them thirdrate after encountering the Fox films Like other Monogram Chan films THE SHANGHAI COBRA is best left to determined collectors Four stars and thats being generousGFT Amazon Reviewer'

In [ ]:
def remove_punc1(text):
  return text.translate(str.maketrans('','',exclude))

Chat_conversion hnadle

In [ ]:
chat_words = {
    'AFAIK':'As Far As I Know',
    'AFK':'Away From Keyboard',
    'ASAP':'As Soon As Possible'
}

In [ ]:
def chat_conversion(text):
  new_text = []
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)

In [ ]:
chat_conversion("Do this work ASAP")

'Do this work As Soon As Possible'

Incorrect text handling

In [ ]:
from textblob import TextBlob

In [ ]:
incorrect_text = "ceertain conditionas durring sevral ggenerations"
textblob = TextBlob(incorrect_text)
textblob.correct().string

'certain conditions during several generations'

Stopwords

In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
len(stopwords.words('english'))

198

In [ ]:
def remove_stopwords(text):
  new_text = []

  for word in text.split():
    if word in stopwords.words('english'):
      new_text.append('')
    else:
      new_text.append(word)
  x = new_text[:]
  new_text.clear()
  return " ".join(x)

In [ ]:
remove_stopwords(df['review'][0])

'Loosely based  novels  Earl Derr Biggers 20th Century Foxs Charlie Chan series proved  audience favoritebut  Japan attacked Pearl Harbor  studio feared audiences would turn   Asian hero This   miscalculation actor Sidney Toler took  role  poverty row Monogram Studios   continued  portray  character  eleven  films made  1944   death  194720th Century Fox  regarded  Chan films  inexpensive B movies  even   studio took considerable care    plots  often silly   pace  sharp  dialogue witty   casts  featured  likes  Bela Lugosi  Ray Milland always expert The result   kindly charm   stood  test  time Monogram   different matter Chan films  B movies plain  simple Little care  taken  scripts  cast  resulting films  flat mediocre  best virtually unwatchable  worstThanks   adequate cast    interesting plot devices THE SHANGHAI COBRA  among  best   Monogrammade Chan filmsbut even   barely manages  achieve  consistent mediocrity In  particularly entry Chan Sidney Toler  called upon  investigate  murderer  kills   appears    cobralike bite    time  decides  make certain   government supply  radium tucked away   bank vault   places remains secure Do  two seemingly unrelated plot lines come together Well could  Sidney Toler  always enjoyable  Chan     Monogram performances seemed phoned inand    true  COBRA      Monogram Chan film As usual  really enjoyable performer  Mantan Mooreland Changing times  led us  look upon Morelands brand  comedy  demeaning  AfricanAmericans     expert actor  comic  taken within  context    possible   black actor   1940s  work  tremendous charm  innocenceFans   20th Century Fox series  likely  find Monograms Chan  significant disappointment  newcomers  like  Monogram films  probably consider  thirdrate  encountering  Fox films Like  Monogram Chan films THE SHANGHAI COBRA  best left  determined collectors Four stars  thats  generousGFT Amazon Reviewer'

Emoji Handle

In [ ]:

import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [ ]:

remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [ ]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 12.0 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [ ]:
import emoji
print(emoji.demojize('Python is 🔥'))

Python is :fire:

Tokenization

In [ ]:
# 1 using the split function
sent = "I am going to banglore"
sent.split()

['I', 'am', 'going', 'to', 'banglore']

In [ ]:
sent1 = "I am going to banglore. i will stay for 1.5years"
sent1.split('.')

['I am going to banglore', ' i will stay for 1', '5years']

In [ ]:
# 2 Regular expression
import re
sent2 = "I am going to banglore"
tokens = re.findall("[\w']+", sent2)
tokens

<>:4: SyntaxWarning: invalid escape sequence '\w'
<>:4: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_615/97112796.py:4: SyntaxWarning: invalid escape sequence '\w'
  tokens = re.findall("[\w']+", sent2)

['I', 'am', 'going', 'to', 'banglore']

In [ ]:
# 3 nltk
from nltk.tokenize import word_tokenize,sent_tokenize
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
sent3 = "I am going to banglore"
word_tokenize(sent3)

['I', 'am', 'going', 'to', 'banglore']

In [ ]:
# spacy
import spacy
nlp = spacy.load('en_core_web_sm')

In [ ]:
doc1 = nlp(sent3)
for token in doc1:
  print(token)

I
am
going
to
banglore

Stemmer

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps = PorterStemmer()
def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

Lemmatization

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [ ]:
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
def lemma_words(text):
  return " ".join([wordnet_lemmatizer.lemmatize(word,pos='v') for word in text.split()])

sample1 = "he was running and eating at same time. he has bad habit of swimming after playing long hours in the sun"
lemma_words(sample1)

'he be run and eat at same time. he have bad habit of swim after play long hours in the sun'